# Generated by Django 6.0.6 on 2026-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_field_1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
