apiVersion: batch/v1
kind: Job

metadata:
  name: "{{ .Release.Name }}-migrate"
  labels:
    {{- include "books-catalog-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        {{- include "books-catalog-chart.selectorLabels" . | nindent 8 }}

    spec:
      restartPolicy: Never

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - python
            - manage.py
            - migrate
            - --noinput

          envFrom:
            - configMapRef:
                name: {{ include "books-catalog-chart.fullname" . }}-envs

          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.loadSecretsFrom }}
                  key: password